services:
  nginx:
    image: nginx:1.23
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:80

  backend-soundcloud:
    image: harypham97/hoidanit-backend-soundcloud-public:1.0
    environment:
      PORT: 8008
      MONGO_URL: mongodb+srv://levanhieu12112002:Hieuche12345*@cluster0.qtpqguw.mongodb.net/soudcloud
    ports:
      - 8008:8008

  frontend-nextjs:
    build:
      context: ..
      dockerfile: Dockerfile
    restart: unless-stopped

#docker compose -p hoidanit-soundcloud up -d
#docker compose -p hieuche-soundcloud up -d
